# Generated by Django 4.1 on 2024-03-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Login_time',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Logout_time',
            new_name='logout_time',
        ),
    ]
