# Generated by Django 4.1 on 2024-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Special', max_length=30, null=True),
        ),
    ]
