# Generated by Django 4.1 on 2024-03-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_orderlist_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_no',
        ),
    ]
