# Generated by Django 4.1 on 2024-03-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_orderlist_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.orders'),
        ),
    ]
