# Generated by Django 4.1 on 2024-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
