# Generated by Django 4.1 on 2024-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_orderlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='attend',
            field=models.IntegerField(null=True),
        ),
    ]
