# Generated by Django 4.1 on 2024-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
