# Generated by Django 4.1 on 2024-03-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_orders_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='star',
        ),
    ]
