# Generated by Django 4.1 on 2024-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_orders_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='attend',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
